from __future__ import annotations

from typing import Protocol

import numpy as np


class BaseAgent(Protocol):
    def act(self, state: np.ndarray, eval_mode: bool = False): ...
    def remember(self, transition: tuple): ...
    def update(self): ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
